baseURL = '/'
languageCode = 'cs-CZ'
title = 'svatba Jonáš a Dominika'

[[menu.main]]
    url = "/"
    name = "Úvod"
    weight = 1

[[menu.main]]
    url = "/lokalita/"
    name = "Lokalita"
    weight = 2

[[menu.main]]
    url = "/obrad/"
    name = "Obřad"
    weight = 3

[[menu.main]]
    url = "/veselka/"
    name = "Veselka"
    weight = 4

[[menu.main]]
    url = "/ubytovani/"
    name = "Ubytování"
    weight = 5

[[menu.main]]
    url = "/saris/"
    name = "Šariš"
    weight = 6

[[menu.main]]
    url = "/slovnik/"
    name = "Slovník"
    weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
